# @todo to be replaced with proper semantic config ?

parameters:

    kaliop_queueing_sqs.default.client_config:
        credentials:
            key: ""
            secret: ""
        # @see http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Common.Enum.Region.html
        region: "us-east-1"
        # NB: It is recommended to fix a specific version for production
        version: "latest"
        # to get even more debug info that is available via command line switches, use:
        #debug: true

    # The number of messages to download in a single request to the sqs API.
    # Bigger numbers will give better performances, but the API is rate-limited: the size of a single response
    # should not exceed 2MB and 10.000 items.
    kaliop_queueing_sqs.default.request_batch_size: 1

    # sample configuration: consumer queues
    kaliop_queueing_sqs.default.consumers:
        examplequeuename:
            callback: kaliop_queueing.message_consumer.http_request
