language: php

# This should make the builds faster
sudo: false

php:
  # aws-sdk-php needs php >+ 5.5
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    # encrypte env vars to use for Symfony config
    - secure: "oTj5V1n8VaoskaxVFutiPw4p0HlHTH8jJBg0fFNaOTuzVIJGFvEPImLsD69erUMqakIWpRdzqsQ97MI/CNLDAuK/QPB+Nc2JAvzGuXEXVMxa1nGLdelQs6Ggiw1b8oeGec9lzVMnTcxbgqyiCFy+mPfPD6QFPufq3Pz5SbMdKdSjUJjCaNyW/gmN/N10TOkVDV5QzsGkxoFOpOxaRcBluFGv/rZOywLnBCtcbLLhgSLllAUcTgfoTi9c2CajssbFVS5B3QwF2Wge4g4kUc+VEnpUrnf8pEv2D0M1uM2q8kXdBbn1m56bk3E2Ab8txMox5jGGIO54J3A6IVf+jJbL9CruAksYSqn9RQdeNvi3/1yVTXBTj51DRP3nTR7kzQ7kCIwZt2cbzNwNpBUAZTvUQ4tlPk1O9AihrKzRyLKBAmIitLspYZUmpBWWlvEDuX5VYKQWYX0FBEv1L7sID2hcqjECR+JsQOGVRSSqsfNbAqA/wPwdlM0rhd/lvEn4thCt33rmpaSGW2ORFkGTFCfII6iRb70eew6cHPQdM9um0tUU2aAqrSbZH2OCNjOClP+2C8YbfiZu6e3BKWmt/C4NFGVvObNXnN8="
    - secure: "S2Z6KOmxD0Kl39/6BfEHlSdvROqPG63YWldoiN2TZ0GGUeLW2blhsZDDQCqXG4yLNBedhNOccLlglWh5Z9Tj8hDdmLbgzNoDZiEQUyeZnYrGuvV4moIkJNPBZdsdbyusPez9X24umj55tkRAigSpAzCK3JZqUIgtOmneekvDAvLeoJGVF3C4mUj8/aJ+E2zCki0cYzdXBMY5FA/4Trbhf501NpqZgftei2PVka2q/6JTIMJN40lQJAmOht8sC1WZfUfVDRfIS6gKGOWf/efjg+N39VojdMaz33A8zpFBEcq+d9GHb7VhbtF/B5ONyZuXoGOr96kQHnevSfuIqnBAiCBMHvNXT0fd7JTx2GclZfwkcXNOanQUjTU9Zd1rGT1VagI0dhyWeGKqnnYopAMCjSywbYHjg4DEovSWZed8SKlx8leiNqlzRuJHCGfC4ZcWl4Py5QtlW7axzXLtqg1Inu8bJAyP9sA8PmLvFa88nZNeJHSr/wYRTPWH4cDPBSMP/eM61wk7qMGU1q+DNcwpIISn4cmlK9Sxuj2mbcXKs9XyYiWpM+qVvPaKA5rBJisMLqhvZ6+nKUVzRwXD4kRTEhrlw8lt4DE="
  matrix:
    # Test only on versions of Sf that are still supported
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*

matrix:
  allow_failures:
    # at the moment it gives an error with Sf 2.6 and 2.7...
    - php: 7.0

before_install:
  # This is mandatory or 'apt-get install' calls following will fail
  #- sudo apt-get update -qq

install:
  - composer self-update
  - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}
  - composer install

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  phpunit --coverage-clover=coverage.clover Tests/phpunit

after_failure:
  # Display as much info as we can to help developers
  #- cat apache_error.log
  #- cat apache_access.log
  #- cat /var/log/hhvm/error.log
  #- if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then php -i; fi

after_script:
  # Upload code-coverage to Scrutinizer
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
  # Upload code-coverage CodeClimate
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then CODECLIMATE_REPO_TOKEN=TOBEGOTTEN ./vendor/bin/test-reporter --coverage-report=coverage.clover; fi

cache:
  directories:
    - $COMPOSER_CACHE_DIR
